ssh_keys:
    - name: meshkat
      email: meshkat632@gmail.com
      type: ed25519
      created: "2026-09-22T10:57:17Z"
      public_key: |
        ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEUt2LCEXm2uTxeKYjlG4OvOkzegBLrdtrBsDS277LRE meshkat632@gmail.com
      private_key: ENC[AES256_GCM,data:maShSPZ99sFAfA8h6p6cNDXdWL/jX9PVzfS6i92ZIkVpJnwiJZsz/EbgLuwDADmOHfVHG1S9nipYQsFeEg5u03QWORs1kXz7wIC2/MJqoViiiPBCywq3V9p/wQscfARH3qmmG3XsvmrYks9Ns646zIcXG3FoAuc5k2McTyBrdOkriqSt2UB4SLhiiRQ+wdF5OxhwBPXUdcY+49Mk+DLbOeFSwwK1ePxqafFpcpebxcrmFJbEiiVGf0LKZ/gMtDz/XcUrMdVcp69g0QTnmaACUJZ1MJYAQbq3W2kulU2/gkf6wK8zyPOs3WBW+bQbtzaB+Wye/CWe6aNfjEn2lVUipsMJQZuaOjCoY8KbChZSYyjQUN1npTk5RhhqLHDmEMfLGsbaIOQKFCqjSiKmZ33f4pqa+0/qD5av77p7WYY0xoAriw47PerZi57h27xOsoR/6qwuirijpCyglKazxlCFKDOD7ClhDBMgcRGMZEdExPIGlTCrUrCUF/JPV1E7TbjsUDEfijeu+X4wcRAcMJZ/2ig2Z0NPTvja6Fy0,iv:1j2rmxZvgX6HboG/YkwXaSIw43yK7z7Z9HwKI7u0z0A=,tag:OINn9p0IRc35fsNb3aqiPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzmfv9re2cgdgts9d8ww4zhlxzgudud3t00ev8aftd6w7zndyp4srhjyqp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSVJ0VjBaRzZmelpLQUpp
            MWs2S3ZNMmZudEdlYXlZWDZUOHVFVUxCSEhVCmppd1VRdDZOS1BZWWFrU1BCQ1ZY
            dnZVQWtsUzl4SFVxOXlwT1ZWdTN0YWcKLS0tIFNhSlU2dkRVTUh2d1lnNFVPdS9v
            U1JTSGdoaTd3N3NvdW90enIyRkpHb3MKZ5JqAG9aXGA3FzddqDpKTMn6pEMm5W6p
            Y9brun4R+7HhbYcNWY+9vRpdADX0Q6ULSeCC86TLOYu9GudmE8xLfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e8r8s0j29ujrwtu62swg8tttw9rrrnnlgg6svdkn3gfxffh7zemq3nj9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa0RDeVd4MjEyakFSZVhB
            OHN0RjRvMUxVSEgrKzgwT1lHekpxZWtWQlRjCnZsWUZTRElDQWFZSC9YM0l5Ukll
            cnB4SXUxS2JXVE43Z1R1WHQ1S280UmsKLS0tIDhFKzl3TVdTNjExSjVaSlorMWRi
            M3hrQUtBN3B0QUZCa0NuaUprMngyRlEK8IMGVlFvXYPNwEB+U2hTcEe8IufMWYFg
            +hF0VrinlsvLNoJlssEGhZKDQEYS5VQLFVvVeyqmctiFMKNmjot36Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T11:03:27Z"
    mac: ENC[AES256_GCM,data:/xCRORENfYkQM4RVQHukIwA2fIcLtVrvSJCa8OBBWwyW7RUb8hF1fdJbukWqp/B/aZPL4rG5k/tO9Dkwfeby/RkllRwbIL2eLOr9D6pjJfzspc2YXEMKr/pBsQ/f5QDBcKF+8AWRQQpqRMlJ4c1KjqhVLgHgszr//arqHEDFJZ0=,iv:PMJA9hce5OClx1uQovKDvwmR5a+O6p30H2WxauO6DRk=,tag:a2PtFx8ZLKRlBPpDFAPugQ==,type:str]
    pgp: []
    encrypted_regex: ^(password|api_key|token|private_key)$
    version: 3.9.0
