db:
    username: admin
    password: ENC[AES256_GCM,data:BtCnels=,iv:6k7qA8BWSYSUfqjp1U2FVGBGn1QBMQH76NieVUE2MFs=,tag:Z+QS3BGIKpMm26yPPfARrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzmfv9re2cgdgts9d8ww4zhlxzgudud3t00ev8aftd6w7zndyp4srhjyqp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPK1U2TGp4VUhWQW9lOE5F
            Y0UxWUpxVGNCTnZ3RTVkSlFMVmNxZWU0Mnp3CmUwcVR5ZTg3amQ2NXRLSTZFY1ZL
            azZUd3F1Skh1S042Y0FSR3c0UGlGejAKLS0tIDZSSjBrTUMrU01qckJ1TWdsZGN2
            WVRvZ0Fza3BsbnhjbkU4WFhDK3JWVTQKYFkvqdcwX2sUzktHGsib3xEpZgiBCBXv
            +QoFtJEgOtE2JrtMBhuCwdLplKrJBwWNcXQHjWZ1gUFtmwhrdIFzhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e8r8s0j29ujrwtu62swg8tttw9rrrnnlgg6svdkn3gfxffh7zemq3nj9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZjdJUk1hT1VhN0ZwN3Fn
            azRvZUZPUHZCUTd5aE91OXNYZ01oTytwRWhBCnkzWXNkQmdEa1J5OHFIbkh4d0dZ
            Sm1xM2pkZ3JtekVjakI5QmxmRmZKYzAKLS0tIGJQRkF0RllKZDhXTmNKNDU5Wklk
            VVhZRWhzN2t5WXpwU05iMHdSWXRYYVUKc0Re9PgHcy8f092CDd/aEHYEyMloMR75
            +JQwSfmmSnboDg8V5oKDMd+jfaadANy5zeXhT4vpXl9u/92n6JGg5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T11:03:27Z"
    mac: ENC[AES256_GCM,data:PX8X9xkr6HMCKLZsmi8YZwnC0zXjWiXprst/Bb61YctaP0A0410b2loKMtB/yIwZqcLEygDy3oXrcpw0VoaZNYNDjOiI1qerrxHxELsTjp12wKOhyRzzMztUhABUCyPQhr6gep4Fia934QjUcrYRSIpXMNKXI3ESKvLdwcq98hs=,iv:BwAkjqIVQTaTzxtI+yux2RdyV7O2gtYGLqg9fBjlZow=,tag:QEB/8Kl93QIrCvX7Ez+JCg==,type:str]
    pgp: []
    encrypted_regex: ^(password|api_key|token|private_key)$
    version: 3.9.0
