db:
    username: ENC[AES256_GCM,data:TEWhPKo=,iv:nPdWBYQx24rJEx0XWL7JUBR2fj6kMuMELbWnyIsWItU=,tag:i1WiSC64eUk1YMNzWl7cEA==,type:str]
    password: ENC[AES256_GCM,data:rvP+sCM=,iv:xGGG4Mfa8H3RsouQRNNK3SwmbsYHUw//2iUf/YdYbUI=,tag:nKhDwEncgEdZdvj4Ltj4OQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzmfv9re2cgdgts9d8ww4zhlxzgudud3t00ev8aftd6w7zndyp4srhjyqp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdDR1cWJoZVh0NWRkMnQr
            WXlCVDROemhQZTk1UDFSRVlaQWVPL1NZdDFJCkNpa2o5RWdubVlDaGtaZVNGd0hL
            dTEyZlB2dXRDZDlEQUkvdFUxNURvckEKLS0tIDZiQ0ViMXVxRlFkYkdHSmM1eC96
            OXFYdnZrZHpOODF2bng2M1RkVWlURDgKbw8I3SQm+8DobEVeCdcDL/LVl6Ol0M9v
            WtZ4a7xRLX2sFvV129sy1Kr8uwK77bV8hNCNIL9ZSBCozaWjN0owRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e8r8s0j29ujrwtu62swg8tttw9rrrnnlgg6svdkn3gfxffh7zemq3nj9ye
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTzBmTjlsOG9TM1RwRjFC
            M0NXVk1yN2YrdGh1Ly9XYTBMOXZydThEY1VzCmV2MG45VUxKZU5WQUdNZE5GbWJs
            SWRHU1kvT3hPOHFOeGt1VERUdTBnZWcKLS0tIDNLWEk3aDBHa3p1WU9YSDRkWENH
            cWdWd3RTUndGWnFsS1h1VkdCTVdWNm8KKmBmQX6x/nrrXuYkumILusFPmlB8nsoV
            BQo0T+pxHU1aXa6HUD9fs9bCxDBEwSXiuXi6U1sWFXdWZ759AKpq1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T09:35:45Z"
    mac: ENC[AES256_GCM,data:BQfiG8AqCLqA/l4e8FRxE+EnpZIlibH9DcDkCQAcRwjN8vw8uatKN7vsYT+gUbC6BXFgPwY52f1zQS6QGq7J3KdP5qhn660vMZC7Y4SxWInYXgEcW1Evt1yZy/xAsY73AYThYk4yP5x8Q8hkv8Y0fNouSOMu7K9oHE7iyqzJjCg=,iv:TJY3dg5MsMOfYT/Tr+3ZnhsK3m34p47oTpVHRVjUI0Q=,tag:Xo18MnyeZTwqnJyDkqUo7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
