variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "key_name" {
  description = "Name for the AWS key pair"
  type        = string
  default     = "k0stool-key"
}

variable "public_key_path" {
  description = "Path to the public key generated by `make keypair`"
  type        = string
  default     = "~/.k0stool/k0stool-key.pub"
}
